services:
  db:
    image: postgres:14
    restart: always
    container_name: postgresql
    volumes:
      - db-data:/var/lib/postgresql/data  # Usamos un volumen anónimo
    environment:
      POSTGRES_DB: prueba_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_NAME=prueba_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    depends_on:
      - db
volumes:
  db-data:  # Definir un volumen anónimo
