# Generated by Django 5.1 on 2024-09-04 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('tienda', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='pedido_id',
        ),
        migrations.RemoveField(
            model_name='lineapedido',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
