# Generated by Django 5.1 on 2024-09-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_lineapedido_pedido_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='adamspay_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='adamspay_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
